### ISSUE TITLE
Install script works

### ISSUE THREAD

**Issue by qkum** [hacker3983/how-to-install-pyrit-on-kali-linux-2020.1a#3]
Hey man, 

I love you.

Your awesome install script just work. (rpi 4, kali linux totally updated) 

You got brain. 

Saving people 1000+ hours every day all over the world.

I wish most in pentest biz was like that. 

If everybody was like you and me we would not have world war, hunger, and all that shit.

And we would have a lot more white hats fighting the black hats in the world. The black hats won't stop as easy as the white hats learning this craft. The white hats can just give up and pick another profession. Crime is digital 2021, they got no real alternative so they will get through it no matter how many 1000+ stressful/frustrating hours it will take.

Because we think and care about others more than most. 

My ending Rant: 

_If it was not for the fk heads in the pentest world who often make it hard on purpose to learn this craft I myself had been a pro now living off it by today. But because the road to mastery is paved with countless errors, outdated shit, half guides, or no guides at all. I'm still jobless 3 years after I started. This is why the world got far from enough white hats. The technical problems are what you use most of your time on learning._ **That is INSANE and it should not be like this.**

**Comment by hacker3983** [comment]
Thank you bro.
 I love you too, I remember sitting in my chair as a 11 years old kid Not knowing what he was doing. trying to fix Pyrit, and learning to hack, trying to find out why it was not working.
I remember playing around with different commands till i got Pyrit working.
I said what if i made a script to do the same thing i did.
I wrote the script took me about 24 hours to complete the script because i was a beginner but i was learning coding.
Started trying to learn to code and hack at 9 years old now i'm 13 years old. I will try to make the script better too.
